// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fingerprintIpIdState struct {
	_          structs.HostLayout
	Counter    uint16
	Pad        uint16
	RandomSeed uint32
}

type fingerprintOsProfile struct {
	_                     structs.HostLayout
	Ttl                   uint8
	DfBit                 uint8
	IpIdBehavior          uint8
	Pad1                  uint8
	WindowSize            uint16
	WindowScale           uint8
	TcpTimestamps         uint8
	Mss                   uint16
	SackPermitted         uint8
	EcnSupport            uint8
	TcpOptionsOrder       [10]uint8
	TcpOptionsCount       uint8
	Pad2                  uint8
	AckInRst              uint8
	Pad3                  uint8
	WindowInRst           uint16
	IcmpQuoteSize         uint8
	IcmpDfInQuote         uint8
	IcmpTtlInQuote        uint8
	IcmpRateLimit         uint8
	UdpClosedPortResponse uint8
	Pad4                  [3]uint8
}

type fingerprintSeqCacheKey struct {
	_     structs.HostLayout
	Saddr uint32
	Sport uint16
	Dport uint16
}

type fingerprintSeqCacheVal struct {
	_      structs.HostLayout
	Seq    uint32
	AckNum uint32
}

// loadFingerprint returns the embedded CollectionSpec for fingerprint.
func loadFingerprint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FingerprintBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fingerprint: %w", err)
	}

	return spec, err
}

// loadFingerprintObjects loads fingerprint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fingerprintObjects
//	*fingerprintPrograms
//	*fingerprintMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFingerprintObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFingerprint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fingerprintSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fingerprintSpecs struct {
	fingerprintProgramSpecs
	fingerprintMapSpecs
	fingerprintVariableSpecs
}

// fingerprintProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fingerprintProgramSpecs struct {
	FingerprintEgress  *ebpf.ProgramSpec `ebpf:"fingerprint_egress"`
	FingerprintIngress *ebpf.ProgramSpec `ebpf:"fingerprint_ingress"`
}

// fingerprintMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fingerprintMapSpecs struct {
	EnabledMap *ebpf.MapSpec `ebpf:"enabled_map"`
	IpIdMap    *ebpf.MapSpec `ebpf:"ip_id_map"`
	ProfileMap *ebpf.MapSpec `ebpf:"profile_map"`
	SeqCache   *ebpf.MapSpec `ebpf:"seq_cache"`
}

// fingerprintVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fingerprintVariableSpecs struct {
}

// fingerprintObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFingerprintObjects or ebpf.CollectionSpec.LoadAndAssign.
type fingerprintObjects struct {
	fingerprintPrograms
	fingerprintMaps
	fingerprintVariables
}

func (o *fingerprintObjects) Close() error {
	return _FingerprintClose(
		&o.fingerprintPrograms,
		&o.fingerprintMaps,
	)
}

// fingerprintMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFingerprintObjects or ebpf.CollectionSpec.LoadAndAssign.
type fingerprintMaps struct {
	EnabledMap *ebpf.Map `ebpf:"enabled_map"`
	IpIdMap    *ebpf.Map `ebpf:"ip_id_map"`
	ProfileMap *ebpf.Map `ebpf:"profile_map"`
	SeqCache   *ebpf.Map `ebpf:"seq_cache"`
}

func (m *fingerprintMaps) Close() error {
	return _FingerprintClose(
		m.EnabledMap,
		m.IpIdMap,
		m.ProfileMap,
		m.SeqCache,
	)
}

// fingerprintVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFingerprintObjects or ebpf.CollectionSpec.LoadAndAssign.
type fingerprintVariables struct {
}

// fingerprintPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFingerprintObjects or ebpf.CollectionSpec.LoadAndAssign.
type fingerprintPrograms struct {
	FingerprintEgress  *ebpf.Program `ebpf:"fingerprint_egress"`
	FingerprintIngress *ebpf.Program `ebpf:"fingerprint_ingress"`
}

func (p *fingerprintPrograms) Close() error {
	return _FingerprintClose(
		p.FingerprintEgress,
		p.FingerprintIngress,
	)
}

func _FingerprintClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fingerprint_bpfeb.o
var _FingerprintBytes []byte
